console.log("a" < "f");



let str = 'Дима балбес, кака-ляля, спун, будильник, печенькаед'
console.log(str.substr(6,7));




let str1 = 'Дима балбес, кака-ляля, спун, будильник, печенькаед'
console.log(str.slice(0, 35));



let str2 = 'Дима балбес, кака-ляля, спун, будильник, печенькаед'
console.log(str.indexOf('спун'));




let str3 = 'Дима балбес, кака-ляля, спун, будильник, печенькаед'
console.log(str.includes('балбес'));
console.log(str.startsWith('Дима'));
console.log(str.startsWith('кака-ляля'));
console.log(str.includes('сбун'));

































































